from .tokens import TokenType

CFG = {
    "<program>": [
        [
            "<global>",
            TokenType.HOME,
            TokenType.OPAR,
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
            "<global>",
        ],
    ],
    "<global>": [
        [
            "<global1>",
            "<next_global>",
        ],
    ],
    "<global1>": [
        [
            TokenType.FROZEN,
            "<fr_primitive_or_object>",
            "<newline>",
        ],
        [
            "<datatype>",
            TokenType.IDENTIFIER,
            "<init_or_func>",
        ],
        [
            TokenType.IDENTIFIER,
            TokenType.IDENTIFIER,
            "<init_or_func>",
        ],
        [
            TokenType.EMPTY,
            TokenType.IDENTIFIER,
            TokenType.OPAR,
            "<parameter>",
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            TokenType.GROUP,
            TokenType.IDENTIFIER,
            "<inheritance>",
            TokenType.COLON,
            "<newline>",
            "<group_body>",
        ],
        [
            None,
        ],
    ],
    "<next_global>": [
        [
            TokenType.GLOBAL,
        ],
        [
            None,
        ],
    ],
    "<init_or_func>": [
        [
            TokenType.ASSIGN,
            "<value>",
            "<newline>",
        ],
        [
            TokenType.OPAR,
            "<parameter>",
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
    ],
    "<inheritance>": [
        [
            TokenType.INHERITS,
            TokenType.IDENTIFIER,
        ],
        [
            None,
        ],
    ],
    "<group_body>": [
        [
            "<tab>",
            "<initialier_or_group_global>",
        ],
    ],
    "<initializer_or_group_global>": [
        [
            "<required_initializer>",
            "<optional_initiliazer>",
            "<optional_group_global>",
        ],
        [
            "<required_group_global>",
            "<optional_initializer>",
            "<optional_group_global>",
        ],
    ],
    "<required_group_global>": [
        [
            "<access_specifier>",
            "<group_global>",
            "<optional_group_global>",
        ],
    ],
    "<group_global>": [
        [
            TokenType.FROZEN,
            "<fr_primitive_or_object>",
            "<newline>",
        ],
        [
            "<data_type>",
            TokenType.IDENTIFIER,
            "<group_init_or_func>",
        ],
        [
            TokenType.IDENTIFIER,
            TokenType.IDENTIFIER,
            "<group_init_or_func>",
        ],
        [
            TokenType.EMPTY,
            TokenType.IDENTIFIER,
            TokenType.OPAR,
            "<parameter>",
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
    ],
    "<group_init_or_func>": [
        [
            TokenType.ASSIGN,
            "<value>",
            "<newline>",
        ],
        [
            TokenType.OPAR,
            "<parameter>",
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            None,
        ],
    ],
    "<optional_group_global>": [
        [
            "<tab>",
            "<-7>"
            "<required_group_global>",
        ],
        [
            None,
        ],
    ],
    "<required_initializer>": [
        [
            TokenType.INITIALIZE,
            TokenType.OPAR,
            "<parameter>",
            TokenType.CPAR,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
    ],
    "<optional_initializer>": [
        [
            "<required_initializer>",
        ],
        [
            None,
        ],
    ],
    "<access_specifier>": [
        [
            TokenType.VISIBLE,
        ],
        [
            TokenType.HIDDEN,
        ],
        [
            TokenType.RESTRICTED,
        ],
    ],
    "<code_block>": [
        [
            "<tab>",
            "<block_definition>",
        ],
    ],
    "<block_definition>": [
        [
            "<statement>",
            "<next_code_block>",
        ],
        [
            TokenType.BACK,
            "<expression>",
        ],
    ],
    "<statements>": [
        [
            "<single_block_statements>",
            "<newline>",
        ],
        [
            "<single_block_statements>",
        ],
    ],
    "<next_code_block>": [
        [
            "<code_block>",
        ],
        [
            None,
        ],
    ],
    "<single_block_statements>": [
        [
            TokenType.GLOBAL,
            TokenType.IDENTIFIER,
        ],
        [
            TokenType.INP,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.OUT,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.STOP,
        ],
        [
            TokenType.SKIP,
        ],
        [
            TokenType.FROZEN,
            "<fr_primitive_or_object>",
        ],
        [
            TokenType.IDENTIFIER,
            "<init_assign_call>",
        ],
        [
            "<object>",
            "<dot_or_assign>",
        ],
        [
            "<castable_type>",
            "<typecast_or_init>",
        ],
        [
            TokenType.WIKI,
            "<collectin_suffix>",
            TokenType.IDENTIFIER,
            TokenType.ASSIGN,
            "<value>",
        ],
        [
            TokenType.CHOICE,
            "<collectin_suffix>",
            TokenType.IDENTIFIER,
            TokenType.ASSIGN,
            "<value>",
        ],
    ],
    "<fr_primitive_or_object>": [
        [
            "<data_type>",
            TokenType.IDENTIFIER,
            TokenType.ASSIGN,
            "<value>",
        ],
        [
            TokenType.IDENTIFIER,
            TokenType.IDENTIFIER,
            TokenType.ASSIGN,
            "<value>",
        ],
    ],
    "<typecast_or_init>": [
        [
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            "<collection_suffix>",
            TokenType.IDENTIFIER,
            TokenType.ASSIGN,
            "<value>",
        ],
    ],
    "<init_assign_call>": [
        [
            TokenType.IDENTIFIER,
            "<assign_operator>",
            "<value>,"
        ],
        [
            "<assign_call>",
        ],
    ],
    "<assign_call>": [
        [
            "<dot_tail>",
        ],
        [
            "<assign_operator>",
            "<value>",
        ],
        [
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
            "<dot_tail>",
        ],
        [
            "<slice_suffix>",
            "<dot_or_assign>",
        ],
    ],
    "<dot_tail>": [
        [
            TokenType.PERIOD,
            "<id_or_coll_func>",
        ],
        [
            None,
        ],
    ],
    "<id_or_coll_func>": [
        [
            TokenType.IDENTIFIER,
            "<assign_call>",
        ],
        [
            "<object>",
            "<dot_or_assign>",
        ],
        [
            "<collection_func>",
        ],
    ],
    "<dot_or_assign>": [
        [
            TokenType.PERIOD,
            "<id_or_coll_func>",
        ],
        [
            "<assign_operator>",
            "<value>",
        ],
    ],
    "<multi_block_statements>": [
        [
            TokenType.INCASE,
            "<multi_block_expression>",
            TokenType.COLON,
            "<newline>",
            "<code_block>",
            "<unless>",
            "<instead>",
        ],
        [
            TokenType.GIVEN,
            "<given_value>",
            TokenType.COLON,
            "<newline>",
            "<event>",
            "<default>",
        ],
        [
            TokenType.EVERY,
            "<data_type>",
            TokenType.IDENTIFIER,
            "<opt_pair>",
            TokenType.IN,
            "<iterable>",
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            TokenType.GO,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
            "<tab>",
            TokenType.DURING,
            "<multi_block_expression>",
            "<newline>",
        ],
        [
            TokenType.DURING,
            "<multi_block_expression>",
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            "<expression>",
        ],
        [
            TokenType.OPAR,
            "<expression>",
            TokenType.CPAR,
        ],
    ],
    "<unless>": [
        [
            "<tab>",
            TokenType.UNLESS,
            "<multi_block_expression>",
            TokenType.COLON,
            "<newline>",
            "<code_block>",
            "<next_unless>",
        ],
        [
            None,
        ],
    ],
    "<next_unless>": [
        [
            "<unless>",
        ],
        [
            None,
        ],
    ],
    "<instead>": [
        [
            "<tab>",
            TokenType.INSTEAD,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            None,
        ],
    ],
    "<given_value>": [
        [
            TokenType.IDENTIFIER,
            "<variable_tail>",
        ],
        [
            TokenType.OPAR,
            TokenType.IDENTIFIER,
            "<variable_tail>",
            TokenType.CPAR,
        ],
    ],
    "<event>": [
        [
            "<tab>",
            TokenType.EVENT,
            "<event_value>",
            TokenType.COLON,
            "<newline>",
            "<code_block>",
            "<next_event>",
        ],
    ],
    "<event_value>": [
        [
            TokenType.WORD_LITERAL,
        ],
        [
            TokenType.NUM_LITERAL
        ],
        [
            TokenType.DECI_LITERAL,
        ],
        [
            TokenType.YES,
        ],
        [
            TokenType.NO,
        ],
    ],
    "<next_event>": [
        [
            "<newline>",
            "<event>",
        ],
        [
            None,
        ],
    ],
    "<default>": [
        [
            "<tab>",
            TokenType.DEFAULT,
            TokenType.COLON,
            "<newline>",
            "<code_block>",
        ],
        [
            None,
        ],
    ],
    "<opt_pair>": [
        [
            TokenType.COMMA,
            "<data_type>",
            TokenType.IDENTIFIER,
        ],
        [
            None,
        ],
    ],
    "<iterable>": [
        [
            "<collection_value>",
        ],
        [
            "<wiki_value>",
        ],
        [
            "<func_or_var>",
        ],
        [
            TokenType.RANGE,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.WORD_LITERAL,
        ],
    ],
    "<data_type>": [
        [
            TokenType.NUM,
            "<collection_suffix>",
        ],
        [
            TokenType.WORD,
            "<collection_suffix>",
        ],
        [
            TokenType.DECI,
            "<collection_suffix>",
        ],
        [
            TokenType.CHOICE,
            "<collection_suffix>",
        ],
        [
            TokenType.IDENTIFIER,
            "<collection_suffix>",
        ],
    ],
    "<castable_type>": [
        [
            TokenType.NUM,
        ],
        [
            TokenType.WORD,
        ],
        [
            TokenType.DECI,
        ],
    ],
    "<return_type>": [
        [
            TokenType.EMPTY,
        ],
        [
            "<data_type>",
        ],
    ],
    "<collection_suffix>": [
        [
            TokenType.OBRACK,
            "<collection_index>",
            TokenType.CBRACK,
            "<next_collection_suffix>",
        ],
        [
            None,
        ],
    ],
    "<next_collection_suffix>": [
        [
            "<collection_suffix>",
        ],
        [
            None,
        ],
    ],
    "<collection_index>": [
        [
            TokenType.NUM_LITERAL,
        ],
        [
            "<func_or_var>",
        ],
        [
            TokenType.OBRACK,
            "<value>",
            "<next_item>",
            TokenType.CBRACK,
        ],
    ],
    "<next_item>": [
        [
            TokenType.COMMA,
            "<value>",
            "<next_item>",
        ],
        [
            None,
        ],
    ],
    "<predefined_func>": [
        [
            TokenType.RANGE,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.INP,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.OUT,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.WORD,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.NUM,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.DECI,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
    ],
    "<collection_func>": [
        [
            TokenType.COL_ADD,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.COL_DELETE,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.COL_DELETE_AT,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            None,
        ],
    ],
    "<slice_suffix>": [
        [
            TokenType.OBRACK,
            "<slice_operand>",
            "<slice>",
            TokenType.CBRACK,
        ],
    ],
    "<slice>": [
        [
            TokenType.COLON,
            "<slice_operand>",
        ],
        [
            None,
        ],
    ],
    "<slice_operand>": [
        [
            TokenType.NUM_LITERAL,
        ],
        [
            "<func_or_var>",
        ],
    ],
    "<object>": [
        [
            TokenType.PARENT,
        ],
        [
            TokenType.SELF,
        ],
    ],
    "<func_or_var>": [
        [
            TokenType.IDENTIFIER,
            "<func_or_var_tail>",
        ],
        [
            "<object>",
            "<variable_tail>",
        ],
    ],
    "<func_or_var_tail>": [
        [
            "<variable_tail>",
        ],
        [
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
            "<func_or_var_tail>"
        ],
        [
            None,
        ],
    ],
    "<variable_tail>": [
        [
            TokenType.PERIOD,
            "<next_dot_operand>",
            "<variable_tail>",
        ],
        [
            "<splice_suffix>",
            "<variable_tail>",
        ],
        [
            None,
        ],
    ],
    "<next_dot_operand>": [
        [
            TokenType.IDENTIFIER,
        ],
        [
            "<object>",
        ],
    ],
    "<parameter>": [
        [
            "<data_type>",
            TokenType.IDENTIFIER,
            "<next_parameter>",
        ],
        [
            None,
        ],
    ],
    "<next_parameter>": [
        [
            TokenType.COMMA,
            "<parameter>",
        ],
        [
            None,
        ],
    ],
    "<argument>": [
        [
            "<expression>",
            "<next_argument>",
        ],
        [
            None,
        ],
    ],
    "<next_argument>": [
        [
            TokenType.COMMA,
            "<argument>",
        ],
        [
            None,
        ],
    ],
    "<newline>": [
        [
            TokenType.NEWLINE,
            "<next_newline>",
        ],
        [
            TokenType.EOF,
        ],
    ],
    "<next_newline>": [
        [
            TokenType.NEWLINE,
            "<next_newline>",
        ],
        [
            None,
        ],
    ],
    "<tab>": [
        [
            TokenType.TAB,
            "<next_tab>",
        ],
    ],
    "<next_tab>": [
        [
            "<tab>",
        ],
        [
            None,
        ],
    ],
    "<value>": [
        [
            "<expression>",
        ],
        [
            "<collection_value>",
        ],
        [
            "<wiki_value>",
        ],
    ],
    "<expression>": [
        [
            "<disjunction>",
        ],
    ],
    "<disjunction>": [
        [
            "<conjunction>",
            "<next_disjunction>",
        ],
    ],
    "<next_disjunction>": [
        [
            TokenType.OR,
            "<disjunction>",
        ],
        [
            None,
        ],
    ],
    "<conjunction>": [
        [
            "<inversion>",
            "<next_conjunction>",
        ],
    ],
    "<next_conjunction>": [
        [
            TokenType.AND,
            "<conjunction>",
        ],
        [
            None,
        ],
    ],
    "<inversion>": [
        [
            TokenType.NOT,
            "<inversion>",
        ],
        [
            "<comparison>",
        ],
    ],
    "<comparison>": [
        [
            "<sum>",
            "<comparison_operand>",
        ],
    ],
    "<comparison_operand>": [
        [
            "<comparison_operator>",
            "<sum>",
        ],
        [
            None,
        ],
    ],
    "<comparison_operator>": [
        [
            TokenType.LESS_THAN,
        ],
        [
            TokenType.LESS_THAN_EQUAL,
        ],
        [
            TokenType.GREATER_THAN,
        ],
        [
            TokenType.GREATER_THAN_EQUAL,
        ],
        [
            TokenType.NOT_EQUAL,
        ],
        [
            TokenType.EQUAL_TO,
        ],
    ],
    "<sum>": [
        [
            "<term>",
            "<next_term>",
        ],
    ],
    "<term>": [
        [
            "<factor>",
            "<next_factor>",
        ],
    ],
    "<next_term>": [
        [
            "<term_operator>",
            "<sum>"
        ],
        [
            None,
        ],
    ],
    "<term_operator>": [
        [
            TokenType.PLUS,
        ],
        [
            TokenType.MINUS,
        ],
    ],
    "<factor>": [
        [
            "<atom>",
            "<exponentiation>",
        ],
    ],
    "<next_factor>": [
        [
            "<factor_operator>",
            "<term>",
        ],
        [
            None,
        ],
    ],
    "<factor_operator>": [
        [
            TokenType.MULTIPLY,
        ],
        [
            TokenType.DIVIDE,
        ],
        [
            TokenType.FLOOR,
        ],
        [
            TokenType.MODULO,
        ],
    ],
    "<exponentiation>": [
        [
            TokenType.POWER,
            "<factor>",
        ],
        [
            None,
        ],
    ],
    "<atom>": [
        [
            TokenType.WORD_LITERAL,
            "<type_cast_tail>",
        ],
        [
            "<numeric>",
            "<type_cast_tail>",
        ],
        [
            TokenType.MINUS,
            "<numeric>",
        ],
        [
            TokenType.YES,
        ],
        [
            TokenType.NO,
        ],
        [
            TokenType.NEW,
            TokenType.IDENTIFIER,
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
        [
            TokenType.OPAR,
            "<expresson>",
            TokenType.CPAR,
        ],
        [
            TokenType.BLANK,
        ],
        [
            "<func_or_var>",
        ],
    ],
    "<numeric>": [
        [
            TokenType.NUM_LITERAL,
        ],
        [
            TokenType.DECI_LITERAL,

        ],
    ],
    "<type_cast_tail>": [
        [
            TokenType.OPAR,
            "<argument>",
            TokenType.CPAR,
        ],
    ],
    "<wiki_value>": [
        [
            TokenType.OBRACE,
            TokenType.WORD_LITERAL,
            TokenType.COLON,
            "<value>",
            "<next_pair>",
            TokenType.CBRACE,
        ],
    ],
    "<next_pair>": [
        [
            TokenType.COMMA,
            TokenType.WORD_LITERAL,
            TokenType.COLON,
            "<expression>",
            "<next_pair>",
        ],
        [
            None,
        ],
    ],
    "<assign_operator>": [
        [
            TokenType.ASSIGN,
        ],
        [
            TokenType.PLUS_ASSIGN,
        ],
        [
            TokenType.MINUS_ASSIGN,
        ],
        [
            TokenType.MULTIPLY_ASSIGN,
        ],
        [
            TokenType.DIVIDE_ASSIGN,
        ],
        [
            TokenType.FLOOR_ASSIGN,
        ],
        [
            TokenType.POWER_ASSIGN,
        ],
        [
            TokenType.MODULO_ASSIGN,
        ],
    ],
}